import {
  Product,
  Category,
  InventoryMovement,
  StockAlert,
  InventoryStats,
} from "./types";

export const mockCategories: Category[] = [
  {
    id: 1,
    nombre: "Materia Prima",
    descripcion: "Materiales básicos para producción",
    codigo: "MP",
    estado: "activo",
  },
  {
    id: 2,
    nombre: "Productos Terminados",
    descripcion: "Productos listos para la venta",
    codigo: "PT",
    estado: "activo",
  },
  {
    id: 3,
    nombre: "Suministros de Oficina",
    descripcion: "Materiales de oficina y administrativos",
    codigo: "SO",
    estado: "activo",
  },
  {
    id: 4,
    nombre: "Herramientas",
    descripcion: "Herramientas y equipos menores",
    codigo: "HE",
    estado: "activo",
  },
  {
    id: 5,
    nombre: "Consumibles",
    descripcion: "Productos de consumo diario",
    codigo: "CO",
    estado: "activo",
  },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    codigo: "MP-001",
    nombre: "Cemento Portland Tipo I",
    descripcion: "Cemento para construcción general, saco de 42.5kg",
    categoria: "Materia Prima",
    precioCompra: 320.0,
    precioVenta: 380.0,
    stock: 150,
    stockMinimo: 50,
    unidad: "saco",
    ubicacion: "Almacén A-1",
    estado: "activo",
    fechaCreacion: "2024-01-15T00:00:00Z",
    fechaActualizacion: "2024-03-20T10:30:00Z",
  },
  {
    id: 2,
    codigo: "MP-002",
    nombre: "Varilla de Acero 1/2",
    descripcion: "Varilla corrugada de acero grado 40, 12m de longitud",
    categoria: "Materia Prima",
    precioCompra: 850.0,
    precioVenta: 1020.0,
    stock: 25,
    stockMinimo: 10,
    unidad: "unidad",
    ubicacion: "Patio B-2",
    estado: "activo",
    fechaCreacion: "2024-01-20T00:00:00Z",
    fechaActualizacion: "2024-03-18T14:15:00Z",
  },
  {
    id: 3,
    codigo: "PT-001",
    nombre: "Bloque de Concreto 8x8x16",
    descripcion: "Bloque de concreto para construcción",
    categoria: "Productos Terminados",
    precioCompra: 18.5,
    precioVenta: 25.0,
    stock: 5,
    stockMinimo: 50,
    unidad: "unidad",
    ubicacion: "Almacén C-1",
    estado: "activo",
    fechaCreacion: "2024-02-01T00:00:00Z",
    fechaActualizacion: "2024-03-19T09:20:00Z",
  },
  {
    id: 4,
    codigo: "SO-001",
    nombre: "Papel Bond Tamaño Carta",
    descripcion: "Resma de papel bond blanco 20lb, 500 hojas",
    categoria: "Suministros de Oficina",
    precioCompra: 185.0,
    precioVenta: 220.0,
    stock: 35,
    stockMinimo: 20,
    unidad: "resma",
    ubicacion: "Oficina-01",
    estado: "activo",
    fechaCreacion: "2024-02-15T00:00:00Z",
    fechaActualizacion: "2024-03-15T11:45:00Z",
  },
  {
    id: 5,
    codigo: "HE-001",
    nombre: "Martillo de Goma",
    descripcion: "Martillo de goma 16oz para trabajos delicados",
    categoria: "Herramientas",
    precioCompra: 450.0,
    precioVenta: 540.0,
    stock: 12,
    stockMinimo: 5,
    unidad: "unidad",
    ubicacion: "Herramientas-A",
    estado: "activo",
    fechaCreacion: "2024-03-01T00:00:00Z",
    fechaActualizacion: "2024-03-10T16:30:00Z",
  },
  {
    id: 6,
    codigo: "CO-001",
    nombre: "Guantes de Seguridad",
    descripcion: "Guantes de trabajo con palma recubierta",
    categoria: "Consumibles",
    precioCompra: 125.0,
    precioVenta: 165.0,
    stock: 2,
    stockMinimo: 10,
    unidad: "par",
    ubicacion: "Seguridad-01",
    estado: "activo",
    fechaCreacion: "2024-03-05T00:00:00Z",
    fechaActualizacion: "2024-03-20T08:15:00Z",
  },
];

export const mockMovements: InventoryMovement[] = [
  {
    id: 1,
    productId: 1,
    tipo: "entrada",
    cantidad: 50,
    precioUnitario: 320.0,
    motivo: "Compra a proveedor ABC",
    referencia: "COMP-2024-001",
    fecha: "2024-03-20",
    usuario: "Juan Pérez",
    fechaCreacion: "2024-03-20T10:30:00Z",
  },
  {
    id: 2,
    productId: 3,
    tipo: "salida",
    cantidad: 100,
    precioUnitario: 18.5,
    motivo: "Venta al cliente XYZ",
    referencia: "VENT-2024-015",
    fecha: "2024-03-19",
    usuario: "María González",
    fechaCreacion: "2024-03-19T15:45:00Z",
  },
  {
    id: 3,
    productId: 6,
    tipo: "salida",
    cantidad: 8,
    precioUnitario: 125.0,
    motivo: "Uso interno - Proyecto Norte",
    referencia: "USO-2024-003",
    fecha: "2024-03-18",
    usuario: "Carlos López",
    fechaCreacion: "2024-03-18T14:20:00Z",
  },
  {
    id: 4,
    productId: 2,
    tipo: "ajuste",
    cantidad: -2,
    precioUnitario: 850.0,
    motivo: "Ajuste por inventario físico",
    referencia: "AJU-2024-001",
    fecha: "2024-03-17",
    usuario: "Ana Martínez",
    fechaCreacion: "2024-03-17T16:00:00Z",
  },
  {
    id: 5,
    productId: 4,
    tipo: "entrada",
    cantidad: 20,
    precioUnitario: 185.0,
    motivo: "Compra mensual oficina",
    referencia: "COMP-2024-002",
    fecha: "2024-03-15",
    usuario: "Luis Rodríguez",
    fechaCreacion: "2024-03-15T11:45:00Z",
  },
];

export const mockStockAlerts: StockAlert[] = [
  {
    productId: 3,
    codigo: "PT-001",
    nombre: "Bloque de Concreto 8x8x16",
    stockActual: 5,
    stockMinimo: 50,
    diferencia: -45,
    categoria: "Productos Terminados",
    nivel: "critico",
  },
  {
    productId: 6,
    codigo: "CO-001",
    nombre: "Guantes de Seguridad",
    stockActual: 2,
    stockMinimo: 10,
    diferencia: -8,
    categoria: "Consumibles",
    nivel: "critico",
  },
  {
    productId: 2,
    codigo: "MP-002",
    nombre: "Varilla de Acero 1/2",
    stockActual: 25,
    stockMinimo: 10,
    diferencia: 15,
    categoria: "Materia Prima",
    nivel: "bajo",
  },
];

export const mockInventoryStats: InventoryStats = {
  totalProductos: 6,
  productosActivos: 6,
  productosInactivos: 0,
  valorInventario: 89525.0, // Valor total al precio de venta
  valorCompra: 74420.0, // Valor total al precio de compra
  productosStockBajo: 1,
  productosStockCritico: 2,
  categorias: 5,
  movimientosHoy: 3,
  margenPromedio: 20.3, // Porcentaje promedio de margen
};
